In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import preprocessing
import pandas as pd
import numpy as np

# Obtain Data

In [3]:
table = pd.read_csv("http://www.simbrain.net/misc/movies_uncleaned.csv", header=-1) #grab data

In [4]:
table.head() # ctrl + '/'

            0         1         2     3       4      5
0  77000000.0  610000.0  9.200000  60.0  6700.0  PG-13
1  63000000.0  720000.0       NaN  65.0  7200.0      R
2  69000000.0  610000.0  9.466667  67.0  6900.0     PG
3        asdf       NaN       NaN   NaN     NaN    NaN
4  64000000.0  720000.0  8.666667  65.0  7300.0  PG-13

In [5]:
table.columns = ["Budget", "Profit", "Average review", "Average age of viewer", "Number of Views", "Film-rating"] # renaming the columns

In [6]:
table.head() # ctrl + '/'

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating
0,77000000.0,610000.0,9.200000,60.0,6700.0,PG-13
1,63000000.0,720000.0,NaN,65.0,7200.0,R
2,69000000.0,610000.0,9.466667,67.0,6900.0,PG
3,asdf,NaN,NaN,NaN,NaN,NaN
4,64000000.0,720000.0,8.666667,65.0,7300.0,PG-13

# Cleaning Data

In [7]:
table = table.drop(table.index[3])  #removed row '3'

In [8]:
table.head()

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating
0,77000000.0,610000.0,9.200000,60.0,6700.0,PG-13
1,63000000.0,720000.0,NaN,65.0,7200.0,R
2,69000000.0,610000.0,9.466667,67.0,6900.0,PG
4,64000000.0,720000.0,8.666667,65.0,7300.0,PG-13
5,77000000.0,610000.0,NaN,60.0,7100.0,G

In [9]:
table = pd.get_dummies(table, columns=['Film-rating']) #reorganizing the film rating

In [10]:
table.head()

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating_G,Film-rating_PG,Film-rating_PG-13,Film-rating_R
0,77000000.0,610000.0,9.200000,60.0,6700.0,0,0,1,0
1,63000000.0,720000.0,NaN,65.0,7200.0,0,0,0,1
2,69000000.0,610000.0,9.466667,67.0,6900.0,0,1,0,0
4,64000000.0,720000.0,8.666667,65.0,7300.0,0,0,1,0
5,77000000.0,610000.0,NaN,60.0,7100.0,1,0,0,0

# Impute Data

In [11]:
table = table.fillna(table.mean())

In [12]:
table.head()

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating_G,Film-rating_PG,Film-rating_PG-13,Film-rating_R
0,77000000.0,610000.0,9.200000,60.0,6700.0,0,0,1,0
1,63000000.0,720000.0,8.973196,65.0,7200.0,0,0,0,1
2,69000000.0,610000.0,9.466667,67.0,6900.0,0,1,0,0
4,64000000.0,720000.0,8.666667,65.0,7300.0,0,0,1,0
5,77000000.0,610000.0,8.973196,60.0,7100.0,1,0,0,0

In [13]:
scaler = preprocessing.StandardScaler()
columns_to_rescale = ["Budget", "Profit", "Average review", "Average age of viewer", "Number of Views"]
table[columns_to_rescale] = scaler.fit_transform(table[columns_to_rescale]) #Rescaling Data

In [14]:
table

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating_G,Film-rating_PG,Film-rating_PG-13,Film-rating_R
0,1.692756,-0.844093,0.565954,-1.343420,-1.091740,0,0,1,0
1,-0.824583,1.214577,0.000000,-0.405489,0.255919,0,0,0,1
2,0.254277,-0.844093,1.231378,-0.030317,-0.552676,0,1,0,0
4,-0.644773,1.214577,-0.764895,-0.405489,0.525451,0,0,1,0
5,1.692756,-0.844093,0.000000,-1.343420,-0.013613,1,0,0,0
6,-0.824583,1.588880,-0.432183,-0.593075,0.255919,0,1,0,0
7,-1.184202,0.000000,-1.097607,1.470372,1.873109,0,1,0,0
8,-0.824583,0.653121,-1.097607,1.470372,1.603578,0,0,0,1
9,1.333136,-1.031244,0.565954,-0.968248,-0.822208,1,0,0,0
10,1.512946,-1.218396,-0.099471,-0.968248,-1.091740,0,0,0,1
11,-0.824583,0.653121,-1.430319,1.470372,1.334046,0,0,1,0
12,-1.004393,0.653121,-1.097607,2.033131,1.603578,0,0,0,1
13,-0.644773,0.840273,-1.430319,1.470372,1.334046,0,0,1,0
14,1.333136,-0.844093,0.898666,-1.343420,-0.822208,1,0,0,0
15,-1.184202,1.214577,-1.097607,1.282786,1.334046,0,0,0,1
16,-0.824583,0.840273,-1.097607,-0.593075,-0.013613,0,0,0,1
17,-0.644773,0.840273,-1.097607,-0.405489,-0.013613,1,0,0,0
18,0.074467,-1.218396,0.898666,0.157269,-1.091740,0,1,0,0
19,-1.004393,0.840273,-0.764895,1.470372,1.334046,0,0,0,1
20,-0.824583,1.214577,-0.099471,-0.217903,0.525451,0,0,1,0
21,1.512946,-0.656941,0.898666,-0.780662,-0.822208,1,0,0,0
22,-1.184202,0.840273,-0.764895,1.657958,1.873109,0,1,0,0
23,-0.824583,1.401728,-0.099471,-0.405489,-0.013613,0,0,1,0
24,0.254277,-1.031244,0.565954,0.344855,-0.822208,0,0,0,1
25,-1.004393,0.653121,-1.097607,1.282786,1.873109,0,1,0,0
26,-1.184202,1.027425,-1.430319,1.470372,1.603578,0,0,0,1
27,-0.824583,1.214577,-0.432183,-0.405489,-0.283144,1,0,0,0
28,1.692756,-0.844093,0.565954,-1.155834,-0.822208,0,1,0,0
29,0.074467,-1.405548,0.898666,0.157269,-0.822208,0,0,0,1
30,1.512946,-0.844093,0.898666,-0.968248,-1.361271,0,0,1,0
...,...,...,...,...,...,...,...,...,...
70,-0.824583,1.214577,-1.430319,1.657958,1.334046,1,0,0,0
71,-0.464963,1.214577,-0.099471,-0.217903,0.255919,1,0,0,0
72,1.512946,-0.844093,0.898666,-0.968248,-0.822208,0,0,1,0
73,-1.184202,0.840273,-1.097607,1.282786,1.064514,1,0,0,0
74,0.254277,-0.844093,0.898666,-0.030317,-0.552676,0,0,0,1
75,1.872566,-0.844093,0.233242,-1.155834,-1.091740,0,1,0,0
76,1.692756,-0.656941,0.898666,-1.343420,-0.822208,0,1,0,0
77,1.512946,-0.656941,0.898666,-1.155834,-1.361271,0,0,1,0
78,0.254277,-0.844093,1.231378,0.157269,-0.822208,0,0,0,1
79,-0.285153,1.027425,-0.764895,-0.405489,-0.013613,0,0,1,0
80,-0.644773,0.840273,-1.097607,-0.217903,0.525451,0,0,0,1
81,-0.824583,0.840273,-1.097607,1.845545,1.334046,0,0,0,1
82,-1.184202,0.653121,-1.097607,1.657958,1.334046,0,0,0,1
83,-0.644773,0.840273,-0.764895,1.282786,1.064514,0,1,0,0
84,-0.464963,1.401728,-1.097607,-0.593075,-0.013613,1,0,0,0
85,-0.824583,0.840273,-1.430319,1.657958,1.603578,0,0,0,1
86,-0.644773,1.214577,-0.099471,-0.405489,-0.013613,1,0,0,0
87,1.512946,-1.218396,0.898666,-1.343420,-0.552676,1,0,0,0
88,1.512946,-1.031244,0.898666,-1.531006,-0.822208,0,1,0,0
89,1.512946,-0.844093,0.565954,-1.155834,-0.283144,0,1,0,0
90,-0.105343,-0.844093,0.898666,-0.030317,-0.822208,0,0,1,0
91,0.254277,-1.031244,1.564090,0.157269,-0.283144,0,1,0,0
92,-0.824583,0.653121,-1.097607,1.470372,1.603578,1,0,0,0
93,1.512946,-1.218396,0.898666,-1.155834,-0.822208,0,0,0,1
94,1.872566,-0.656941,0.898666,-1.155834,-1.091740,0,1,0,0
95,-0.644773,1.401728,-1.097607,-0.593075,0.255919,0,0,1,0
96,-0.285153,-0.844093,1.231378,0.157269,-0.552676,1,0,0,0
97,1.333136,-1.218396,0.898666,-1.155834,-0.552676,1,0,0,0
98,0.074467,-1.031244,1.231378,0.344855,-0.822208,1,0,0,0
99,1.512946,-0.844093,0.565954,-0.968248,-0.822208,1,0,0,0

# Export to Simbrain

In [ ]:
table.to_csv("Data_wrangling_table.csv", header=False, index=False) #exporting as a csv file

In [15]:
table.head(10)

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating_G,Film-rating_PG,Film-rating_PG-13,Film-rating_R
0,1.692756,-0.844093,0.565954,-1.343420,-1.091740,0,0,1,0
1,-0.824583,1.214577,0.000000,-0.405489,0.255919,0,0,0,1
2,0.254277,-0.844093,1.231378,-0.030317,-0.552676,0,1,0,0
4,-0.644773,1.214577,-0.764895,-0.405489,0.525451,0,0,1,0
5,1.692756,-0.844093,0.000000,-1.343420,-0.013613,1,0,0,0
6,-0.824583,1.588880,-0.432183,-0.593075,0.255919,0,1,0,0
7,-1.184202,0.000000,-1.097607,1.470372,1.873109,0,1,0,0
8,-0.824583,0.653121,-1.097607,1.470372,1.603578,0,0,0,1
9,1.333136,-1.031244,0.565954,-0.968248,-0.822208,1,0,0,0
10,1.512946,-1.218396,-0.099471,-0.968248,-1.091740,0,0,0,1

In [18]:
output_dataset = pd.DataFrame([[.01,.9],[.7,.2],[.1,.1]], 
   columns = ['Probability Child Will View', 'Probability Adult Will View'])

,Budget,Profit,Average review,Average age of viewer,Number of Views,Film-rating_G,Film-rating_PG,Film-rating_PG-13,Film-rating_R
0,1.692756,-0.844093,0.565954,-1.343420,-1.091740,0,0,1,0
1,-0.824583,1.214577,0.000000,-0.405489,0.255919,0,0,0,1
2,0.254277,-0.844093,1.231378,-0.030317,-0.552676,0,1,0,0
4,-0.644773,1.214577,-0.764895,-0.405489,0.525451,0,0,1,0
5,1.692756,-0.844093,0.000000,-1.343420,-0.013613,1,0,0,0
6,-0.824583,1.588880,-0.432183,-0.593075,0.255919,0,1,0,0
7,-1.184202,0.000000,-1.097607,1.470372,1.873109,0,1,0,0
8,-0.824583,0.653121,-1.097607,1.470372,1.603578,0,0,0,1
9,1.333136,-1.031244,0.565954,-0.968248,-0.822208,1,0,0,0
10,1.512946,-1.218396,-0.099471,-0.968248,-1.091740,0,0,0,1
11,-0.824583,0.653121,-1.430319,1.470372,1.334046,0,0,1,0
12,-1.004393,0.653121,-1.097607,2.033131,1.603578,0,0,0,1
13,-0.644773,0.840273,-1.430319,1.470372,1.334046,0,0,1,0
14,1.333136,-0.844093,0.898666,-1.343420,-0.822208,1,0,0,0
15,-1.184202,1.214577,-1.097607,1.282786,1.334046,0,0,0,1
16,-0.824583,0.840273,-1.097607,-0.593075,-0.013613,0,0,0,1
17,-0.644773,0.840273,-1.097607,-0.405489,-0.013613,1,0,0,0
18,0.074467,-1.218396,0.898666,0.157269,-1.091740,0,1,0,0
19,-1.004393,0.840273,-0.764895,1.470372,1.334046,0,0,0,1
20,-0.824583,1.214577,-0.099471,-0.217903,0.525451,0,0,1,0
21,1.512946,-0.656941,0.898666,-0.780662,-0.822208,1,0,0,0
22,-1.184202,0.840273,-0.764895,1.657958,1.873109,0,1,0,0
23,-0.824583,1.401728,-0.099471,-0.405489,-0.013613,0,0,1,0
24,0.254277,-1.031244,0.565954,0.344855,-0.822208,0,0,0,1
25,-1.004393,0.653121,-1.097607,1.282786,1.873109,0,1,0,0
26,-1.184202,1.027425,-1.430319,1.470372,1.603578,0,0,0,1
27,-0.824583,1.214577,-0.432183,-0.405489,-0.283144,1,0,0,0
28,1.692756,-0.844093,0.565954,-1.155834,-0.822208,0,1,0,0
29,0.074467,-1.405548,0.898666,0.157269,-0.822208,0,0,0,1
30,1.512946,-0.844093,0.898666,-0.968248,-1.361271,0,0,1,0
...,...,...,...,...,...,...,...,...,...
70,-0.824583,1.214577,-1.430319,1.657958,1.334046,1,0,0,0
71,-0.464963,1.214577,-0.099471,-0.217903,0.255919,1,0,0,0
72,1.512946,-0.844093,0.898666,-0.968248,-0.822208,0,0,1,0
73,-1.184202,0.840273,-1.097607,1.282786,1.064514,1,0,0,0
74,0.254277,-0.844093,0.898666,-0.030317,-0.552676,0,0,0,1
75,1.872566,-0.844093,0.233242,-1.155834,-1.091740,0,1,0,0
76,1.692756,-0.656941,0.898666,-1.343420,-0.822208,0,1,0,0
77,1.512946,-0.656941,0.898666,-1.155834,-1.361271,0,0,1,0
78,0.254277,-0.844093,1.231378,0.157269,-0.822208,0,0,0,1
79,-0.285153,1.027425,-0.764895,-0.405489,-0.013613,0,0,1,0
80,-0.644773,0.840273,-1.097607,-0.217903,0.525451,0,0,0,1
81,-0.824583,0.840273,-1.097607,1.845545,1.334046,0,0,0,1
82,-1.184202,0.653121,-1.097607,1.657958,1.334046,0,0,0,1
83,-0.644773,0.840273,-0.764895,1.282786,1.064514,0,1,0,0
84,-0.464963,1.401728,-1.097607,-0.593075,-0.013613,1,0,0,0
85,-0.824583,0.840273,-1.430319,1.657958,1.603578,0,0,0,1
86,-0.644773,1.214577,-0.099471,-0.405489,-0.013613,1,0,0,0
87,1.512946,-1.218396,0.898666,-1.343420,-0.552676,1,0,0,0
88,1.512946,-1.031244,0.898666,-1.531006,-0.822208,0,1,0,0
89,1.512946,-0.844093,0.565954,-1.155834,-0.283144,0,1,0,0
90,-0.105343,-0.844093,0.898666,-0.030317,-0.822208,0,0,1,0
91,0.254277,-1.031244,1.564090,0.157269,-0.283144,0,1,0,0
92,-0.824583,0.653121,-1.097607,1.470372,1.603578,1,0,0,0
93,1.512946,-1.218396,0.898666,-1.155834,-0.822208,0,0,0,1
94,1.872566,-0.656941,0.898666,-1.155834,-1.091740,0,1,0,0
95,-0.644773,1.401728,-1.097607,-0.593075,0.255919,0,0,1,0
96,-0.285153,-0.844093,1.231378,0.157269,-0.552676,1,0,0,0
97,1.333136,-1.218396,0.898666,-1.155834,-0.552676,1,0,0,0
98,0.074467,-1.031244,1.231378,0.344855,-0.822208,1,0,0,0
99,1.512946,-0.844093,0.565954,-0.968248,-0.822208,1,0,0,0